language: c++

dist: trusty

cache:
    directories:
        - Qt

addons:
    apt:
        packages:
            - git
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a subsurface dependency, but a Qt dependency
            - mesa-common-dev

before_install:
    - if [ ! -e Qt/5.8 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-linux-x64-android-5.8.0.run ;
          chmod +x ./qt-opensource-linux-x64-android-5.8.0.run ;
          ./qt-opensource-linux-x64-android-5.8.0.run -platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi

script:
    - perl -pi -e 's/BUILDGRANTLEE=1/BUILDGRANTLEE=0/' scripts/build.sh
    - perl -pi -e 's/BUILDMARBLE=1/BUILDMARBLE=0/' scripts/build.sh
    - perl -pi -e 's/-DNO_PRINTING=OFF/-DNO_PRINTING=ON -DNO_MARBLE=ON -DUSE_WEBENGINE=ON/' scripts/build.sh
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.8/gcc_64/lib/cmake ;
      cd .. ;
      bash -e ./subsurface/scripts/build.sh
#    - cd subsurface/build ; env CTEST_OUTPUT_ON_FAILURE=1 make check
#    - cd subsurface/build-mobile ; env CTEST_OUTPUT_ON_FAILURE=1 make check
